# API
steps:
  - name: 'gcr.io/cloud-builders/yarn'
    args: ['install']
    dir: 'server'
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - kms
      - decrypt
      - --key=cloudbuild-env
      - --keyring=bookily-env
      - --location=global
      - --plaintext-file=.env
      - --ciphertext-file=.env.enc
    dir: 'server'
  - name: 'gcr.io/cloud-builders/yarn'
    args: ['build']
    dir: 'server'
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', 'api.yaml']
    dir: 'server'

  # CLIENT
  - name: 'gcr.io/cloud-builders/yarn'
    args: ['install']
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - kms
      - decrypt
      - --key=cloudbuild-env
      - --keyring=bookily-env
      - --location=global
      - --plaintext-file=.env
      - --ciphertext-file=.env.enc
  - name: 'gcr.io/cloud-builders/yarn'
    args: ['build']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy']
options:
  logging: CLOUD_LOGGING_ONLY
timeout: '1600s'
